openapi: 3.1.0
x-stoplight:
  id: jfs06bc2eocxk
info:
  version: 0.1.0
  title: Device API
  summary: Scarecrow device API
  description: Edge device API for the Scarecrow system
  contact:
    name: Effective Range
    email: info@effective-range.com
    url: 'https://www.effective-range.com'
  license:
    name: MIT
    url: >-
      https://raw.githubusercontent.com/EffectiveRange/scarecrow-api/refs/heads/main/LICENSE
tags:
  - name: device
    description: Edge device
  - name: health
    description: Component health
paths:
  /device/mode:
    post:
      summary: Set mode
      tags:
        - device
      responses:
        '202':
          description: Accepted
        '406':
          description: Not Acceptable
          content:
            application/json:
              schema:
                type: object
                $ref: ./model.yaml#/components/schemas/Error
                x-stoplight:
                  id: il1ogzb1xevrp
      operationId: set-mode
      x-stoplight:
        id: kuqxh4q4g4pes
      description: Set operation mode
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: ./model.yaml#/components/schemas/DeviceEventRequest
              x-stoplight:
                id: urb7rfycr2nwm
  /device/event:
    post:
      summary: Trigger event
      tags:
        - device
      responses:
        '202':
          description: Accepted
        '406':
          description: Not Acceptable
          content:
            application/json:
              schema:
                type: object
                $ref: ./model.yaml#/components/schemas/Error
                x-stoplight:
                  id: il1ogzb1xevrp
      operationId: trigger-event
      x-stoplight:
        id: 2g5wsmpb303i5
      description: Trigger event on device
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: ./model.yaml#/components/schemas/DeviceModeRequest
              x-stoplight:
                id: jlhdkculrapwy
  /health/alive:
    $ref: ./health.yaml#/paths/~1health~1alive
  /health/status:
    $ref: ./health.yaml#/paths/~1health~1status