openapi: 3.1.0
x-stoplight:
  id: eah9hvky64i0x
info:
  version: 0.1.0
  title: Health API
  summary: Scarecrow health API
  description: Component health API for the Scarecrow system
  contact:
    name: Effective Range
    email: info@effective-range.com
    url: 'https://www.effective-range.com'
  license:
    name: MIT
    url: >-
      https://raw.githubusercontent.com/EffectiveRange/scarecrow-api/refs/heads/main/LICENSE
tags:
  - name: health
    description: Component health
paths:
  /health/alive:
    post:
      summary: Signal component is alive
      tags:
        - health
      responses:
        '202':
          description: Accepted
        '400':
          description: Bad Request
        '406':
          description: Not Acceptable
          content:
            application/json:
              schema:
                type: object
                $ref: ./model.yaml#/components/schemas/Error
                x-stoplight:
                  id: 0hnqhhviysnx5
      operationId: health-alive
      x-stoplight:
        id: ut7s2t1utlzxy
      description: Component signals it is alive on the network
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Component'
    parameters: []
  /health/status:
    post:
      summary: Signal component health status
      tags:
        - health
      responses:
        '202':
          description: Accepted
        '400':
          description: Bad Request
        '406':
          description: Not Acceptable
          content:
            application/json:
              schema:
                type: object
                $ref: ./model.yaml#/components/schemas/Error
                x-stoplight:
                  id: kbfu6stjn4fpe
      operationId: health-status
      x-stoplight:
        id: c6t7fqyh58k2o
      description: Component signals its health status
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Component'
    parameters: []
components:
  schemas:
    Component:
      title: Component
      x-stoplight:
        id: 25pz5k69n0j06
      type: object
      required:
        - id
        - uri
        - status_period
      properties:
        id:
          type: string
          x-stoplight:
            id: 5v1abc4gpfj8t
          format: uuid
        uri:
          type: string
          x-stoplight:
            id: b9zjtw0p3orv1
          format: uri
        status_period:
          type: integer
          x-stoplight:
            id: 1l5l2x56fkfin
        session_id:
          type: string
          x-stoplight:
            id: jfbbd24yqwwtq
          format: uuid
        error:
          type: object
          $ref: ./model.yaml#/components/schemas/Error
          x-stoplight:
            id: fzbdyrsbx1rq3