openapi: 3.1.0
x-stoplight:
  id: h0cnxbwl3zz8x
info:
  version: 0.1.0
  title: Common models
  summary: Scarecrow common models
  description: Common models for the Scarecrow system
  contact:
    name: Effective Range
    email: info@effective-range.com
    url: 'https://www.effective-range.com'
  license:
    name: MIT
    url: >-
      https://raw.githubusercontent.com/EffectiveRange/scarecrow-api/refs/heads/main/LICENSE
tags:
  - name: common
    description: Common model
paths: {}
components:
  schemas:
    ErrorCode:
      title: ErrorCode
      x-stoplight:
        id: 7yg0ltsrn3gj6
      enum:
        - unknown
        - unreachable
        - status_expired
        - no_session
        - invalid_argument
        - internal_error
        - local_error
        - invalid_state
      default: unknown
    Error:
      title: Error
      x-stoplight:
        id: il1ogzb1xevrp
      type: object
      required:
        - code
      properties:
        code:
          $ref: '#/components/schemas/ErrorCode'
          x-stoplight:
            id: 7idvowvglir9b
        reason:
          type: string
          x-stoplight:
            id: dan5s6ltwer6v
    DeviceMode:
      title: DeviceMode
      x-stoplight:
        id: ryya533rqjaqp
      enum:
        - manual
        - auto
      default: manual
      type: string
    DeviceEvent:
      title: DeviceEvent
      x-stoplight:
        id: immde7wz73eqj
      enum:
        - buzz
        - bang
      default: buzz
      type: string
    DeviceEventRequest:
      title: EventRequest
      x-stoplight:
        id: csbgt4ne5mxxs
      type: object
      properties:
        event:
          $ref: '#/components/schemas/DeviceEvent'
          x-stoplight:
            id: eqk1r4752syzp
      required:
        - event
    DeviceModeRequest:
      title: DeviceModeRequest
      x-stoplight:
        id: urb7rfycr2nwm
      type: object
      properties:
        mode:
          $ref: '#/components/schemas/DeviceMode'
          x-stoplight:
            id: 0b5wwe54lsdsh
      required:
        - mode